base: 'https://ddev-demo-setup-visual-editor.ddev.site/shadcn'
dependencies:
  - webconsulting/desiderio
  - webconsulting/shadcn2fluid-templates
  - georgringer/news
  - webconsulting/desiderio-template2
  - dirnbauer/adminpanel-defaults
languages:
  -
    title: English
    enabled: true
    locale: en_US.UTF-8
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: English
    flag: us
    languageId: 0
rootPageId: 68
routeEnhancers:
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: /
        _controller: 'News::list'
      -
        routePath: '/page-{page}'
        _controller: 'News::list'
        _arguments:
          page: currentPage
      -
        routePath: '/category/{category-name}/page-{page}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
          page: currentPage
      -
        routePath: '/category/{category-name}'
        _controller: 'News::list'
        _arguments:
          category-name: overwriteDemand/categories
      -
        routePath: '/tag/{tag-name}/page-{page}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags
          page: currentPage
      -
        routePath: '/tag/{tag-name}'
        _controller: 'News::list'
        _arguments:
          tag-name: overwriteDemand/tags
      -
        routePath: '/article/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      news-title:
        type: NewsTitle
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      category-name:
        type: NewsCategory
      tag-name:
        type: NewsTag
settings:
  news.pages.detail: 77
websiteTitle: ''
