base: 'https://ddev-demo-setup-visual-editor.ddev.site/typo3-vienna-camp-2026/'
dependencies:
  - webconsulting/desiderio-preset-corporate
  - marekskopal/typo3-mcp-docs
languages:
  -
    languageId: 0
    title: English
    navigationTitle: English
    locale: en_US.UTF-8
    base: /
    flag: us
    iso-639-1: en
    fallbackType: strict
  -
    languageId: 1
    title: German
    navigationTitle: Deutsch
    locale: de_AT.UTF-8
    base: /de/
    flag: de
    iso-639-1: de
    fallbackType: fallback
  -
    languageId: 2
    title: 'Chinese (Simplified)'
    navigationTitle: 中文
    locale: zh_CN.UTF-8
    base: /zh/
    flag: cn
    iso-639-1: zh
    fallbackType: fallback
  -
    languageId: 3
    title: Hungarian
    navigationTitle: Magyar
    locale: hu_HU.UTF-8
    base: /hu/
    flag: hu
    iso-639-1: hu
    fallbackType: fallback
rootPageId: 505
