plugin:
  tx_solr:
    view:
      partialRootPath: 'EXT:solr_numbered_pagination/Resources/Private/Partials/'
  tx_blog:
    settings:
      blogUid: 15
      categoryUid: 17
      tagUid: 18
      authorUid: 19
      archiveUid: 20
      storagePid: 16
