base: 'https://ddev-demo-setup-visual-editor.ddev.site/14'
dependencies:
  - blog/modern-bootstrap
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 69
routeEnhancers: {  }
websiteTitle: ''
imports:
  -
    resource: 'EXT:blog/Configuration/Routes/Default.yaml'
