base: 'https://ddev-demo-setup-visual-editor.ddev.site/tuga-102/'
dependencies:
  - typo3/form
  - webconsulting/desiderio
  - dirnbauer/adminpanel-defaults
  - webconsulting/desiderio-preset-editorial
  - typo3/fluid-styled-content
languages:
  -
    languageId: 0
    title: English
    navigationTitle: English
    locale: en_US.UTF-8
    base: /
    flag: us
    iso-639-1: en
    fallbackType: strict
  -
    languageId: 1
    title: Deutsch
    navigationTitle: Deutsch
    locale: de_AT.UTF-8
    base: 'https://ddev-demo-setup-visual-editor.ddev.site/tuga-102/de/'
    flag: de
    iso-639-1: de
    fallbackType: fallback
rootPageId: 107
websiteTitle: ''
